<form method="post" action="">
	<table>
		<tr>
			<td>
				<label for="login">Имя</label>
			</td>
			<td>
				<input type="text" id="login" name="login">
			</td>
		</tr>
		<tr>
			<td>
				<label for="password">Пароль</label>
			</td>
			<td>
				<input type="password" id="password" name="password">
			</td>
		</tr>
		<tr>
			<td></td>
			<td>
				<button type="submit">Зарегистрироваться</button>
			</td>
		</tr>
	</table>
</form>